import torch

if __name__ == '__main__':

    print('Test 1 ======================')
    t1 = torch.arange(0, 60).view(3, 4, 5)
    t2 = torch.arange(0, 60).view(3, 5, 4)
    print(t1)
    print(t2)
    t3 = torch.einsum('ijk,ikl->ij', t1, t2)
    print('result:')
    print(t3)

    print('Test 2 ======================')
    # 创建两个张量
    t1 = torch.arange(0, 9).reshape(3, 3)
    print(t1)
    t2 = torch.einsum('ii->i', t1)
    print('result:')
    print(t2)

    print('Test 3 ======================')
    t1 = torch.arange(6).reshape(2, 3)
    print(t1)
    t2 = torch.einsum('ij->', t1)
    print('result:')
    print(t2)

    print('Test 4 ======================')
    t1 = torch.arange(6).reshape(2, 3)
    print(t1)
    t2 = torch.einsum('ij->j', t1)
    print('result:')
    print(t2)

    print('Test 5 ======================')
    t1 = torch.arange(6).reshape(2, 3)
    t2 = torch.arange(3)
    print(t1)
    print(t2)
    t3 = torch.einsum('ik,k->i', t1, t2)
    print('result:')
    print(t3)

    print('Test 6 ======================')
    t1 = torch.arange(6).reshape(2, 3)
    t2 = torch.arange(15).reshape(3, 5)
    print(t1)
    print(t2)
    t3 = torch.einsum('ik,kj->ij', t1, t2)
    print('result:')
    print(t3)

    print('Test 7 ======================')
    t1 = torch.arange(6).reshape(2, 3)
    t2 = torch.arange(6, 12).reshape(2, 3)
    print(t1)
    print(t2)
    t3 = torch.einsum('ij,ij->', t1, t2)
    print('result:')
    print(t3)

    print('Test 8 ======================')
    t1 = torch.arange(3)
    t2 = torch.arange(3, 7)
    print(t1)
    print(t2)
    t3 = torch.einsum('i,j->ij', t1, t2)
    print('result:')
    print(t3)

    print('Test 9 ======================')
    t1 = torch.arange(30).reshape(2, 3, 5)
    t2 = torch.arange(40).reshape(2, 5, 4)
    print(t1)
    print(t2)
    t3 = torch.einsum('ijk,ikl->ijl', t1, t2)
    print('result:')
    print(t3)

    print('Test 10 ======================')
    t1 = torch.arange(6).reshape(2, 3)
    t2 = torch.arange(105).reshape(5, 3, 7)
    t3 = torch.arange(14).reshape(2, 7)
    print(t1)
    print(t2)
    print(t3)
    t4 = torch.einsum('ik,jkl,il->ij', t1, t2, t3)
    print('result:')
    print(t4)

    print('Test 11 ======================')
    t1 = torch.arange(1, 5).reshape(2, 2)
    t2 = torch.arange(5, 9).reshape(2, 2)
    t3 = torch.arange(9, 13).reshape(2, 2)
    t4 = torch.einsum('ij,ik,jk->', t1, t2, t3)
    print('result:')
    print(t4)

# print('Test 11 ======================')
# t1 = torch.arange(210).reshape(2, 3, 5, 7)
# t2 = torch.arange(36465).reshape(11, 13, 3, 17, 5)
# t3 = torch.einsum('pqrs,tuqvr->pstuv', t1, t2)
# print('result:')
# print(t3)
